[package]
name = "dungeoncrawl"
version = "0.1.0"
authors = ["Shlomi Izikovich <shlomii@users.noreply.github.com>"]
edition = "2018"

[dependencies]
bracket-lib = "~0.8.1" #“favor version 0.8.1, but accept patches from the 0.8 base